### ISSUE TITLE
add instructions

### ISSUE THREAD

**Issue by daymos** [fac-cycle/fac-cycle#6]

**Comment by matthewiiv** [comment]
Wiki or README?

**Comment by daymos** [comment]
mmm, not sure. I would go for readme, but have never done it with a wiki.
I have pushed a forst draft. Can you review it?  We could use it as a base for whatever support we choose . Btw, I am not sure if we are preventing commit also for failing the tests...

**Comment by matthewiiv** [comment]
I'm happy with a readme. I think a wiki would be necessary if we wanted to separate project description from dev info. I think we are currently preventing commits if tests don't pass... We just don't have any tests

**Comment by daymos** [comment]
ok seems a good idea.  Rory was asking me yesterday if we had a set of instructions ready for the team. The last pull request should be enough for them to start.
